#!/bin/bash

# Rolls back a release and updates the link hierarchy.
#   depl-help-rollback APP ENVIROMENT [DEPLOYMENT_PATH]
#
# Arguments follow the same logic as with the `deploy` script.
#
# Given the example
#   depl-help-rollback arethusa dev
#
# arethusa-dev-1 will become what was arethusa-dev-2, which itself
# will refers what was arethusa-dev-3 and so on.

source "$(dirname $(readlink -f $0))/depl-help-common.sh"

env=$2
path=${3:-$DEPLOYMENT_HELPER_TARGET}

propagate_links () {
  for i in $(seq 1 $(($total_number - 1))); do
    propagate_link $1 $i
  done
}

propagate_link () {
  new_link=$(link_path $1 $(($2 + 1)))
  if [[ -L $new_link ]]; then
    old_link=$(link_path $1 $2)
    new_target=$(readlink -f $new_link)

    rm $old_link
    create_link $new_target $old_link
  fi
}

propagate_links $env
