#!/bin/bash

# Adds links to versioned builds of your application.
#   deploy APP PATH_TO_BUILD ENVIRONMENT [DEPLOYMENT_PATH]
#
# APP is the name of your application
# PATH_TO_BUILD is the path to the versioned build you want to reference
# ENVIROMENT specifies if linked for the prod or dev environment
# DEPLOYMENT_PATH works the same as in the `setup` script.
#
# Given the example
#   deploy arethusa /usr/local/arethusa/8gh178s prod /var/www/tools/arethusa
#
# A new production link that refers to the directory 8gh178s will be set as
# arethusa-prod-1.
# Older versions will be pushed down the production link stack. The old
# reference of arethusa-prod-1 will then be found in arethusa-prod-2, which
# itself will be pushed down to arethusa-prod-3 and so on.

source ./common.sh

build=$2
env=$3
path=${4:-$DEPLOYMENT_HELPER_TARGET}

cascade_links () {
  for i in $(seq $(($total_number - 1)) -1 1); do
    cascade_link $1 $i
  done
}

cascade_link () {
  old_link=$(link_path $1 $2)
  if [[ -L $old_link ]]; then
    new_link=$(link_path $1 $(($2 + 1)))
    old_target=$(readlink -f $old_link)
    rm $new_link
    ln -s $old_target $new_link
  fi
}

set_new_link () {
  link=$(link_path $1 1)
  rm $link
  ln -s $(readlink -f $build) $link
}

cascade_links $env
set_new_link $env $build
