#!/bin/bash

# Releases the current dev environment into production
#   depl-help-release APP
#
# APP is the name of your application.
#
# Given the example
#   depl-help-release arethusa
#
# The reference of arethusa-dev-1 will be copied and be released
# as arethusa-prod-1.

source "$(dirname $(readlink -f $0))/depl-help-common.sh"

path=${2:-$DEPLOYMENT_HELPER_TARGET}

staging=$(link_path dev 1)
staged_version=$(readlink -f $staging)

$(dirname $(readlink -f $0))/depl-help-deploy $app $staged_version prod $path
