#!/bin/bash

# Releases the current dev environment into production
#   release APP
#
# APP is the name of your application.
#
# Given the example
#   release arethusa
#
# The reference of arethusa-dev-1 will be copied and be released
# as arethusa-prod-1.

source ./common.sh

path=${2:-$DEPLOYMENT_HELPER_TARGET}

staging=$(link_path dev 1)
staged_version=$(readlink -f $staging)

./deploy $app $staged_version prod $path
